import { pool } from "../config/postgres.js";
import fs from 'fs';
import csv from 'csv-parser';
import { env } from "../config/env.js";
import { customerSchema } from "../models/customerSchema.js";

export async function queryTables() {
    const client = await pool.connect();
    
    try {
        
        await client.query('BEGIN');

        await client.query(`
            CREATE TABLE IF NOT EXISTS "supplier" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL,
	"email" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);
        `);

    
        await client.query(`
            
CREATE TABLE IF NOT EXISTS "category" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);
        `);

    
        await client.query(`
    CREATE TABLE IF NOT EXISTS "city" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);
        `);

    
        await client.query(`
            CREATE TABLE IF NOT EXISTS "product" (
	"id" VARCHAR(30) NOT NULL,
	"name" VARCHAR(100) NOT NULL,
	"price" INTEGER NOT NULL,
	"category_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

        `);

    
        await client.query(`
            CREATE TABLE IF NOT EXISTS "order" (
	"id" VARCHAR(30) NOT NULL,
	"date" DATE,
	PRIMARY KEY("id")
);
        `);
        
    
        await client.query(`
            CREATE TABLE IF NOT EXISTS "customer" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL,
	"email" VARCHAR(50) NOT NULL UNIQUE,
	"address" VARCHAR(50) NOT NULL,
	"phone" VARCHAR(50) NOT NULL,
	"city_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);
        `);

    
        await client.query(`CREATE TABLE IF NOT EXISTS "transaction" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"quantity" INTEGER NOT NULL,
	"total_value" INTEGER NOT NULL,
	"product_id" VARCHAR(30) NOT NULL,
	"supplier_id" INTEGER NOT NULL,
	"order_id" VARCHAR(30) NOT NULL,
	"customer_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);`);
    

    
        await client.query(`
ALTER TABLE "product"
ADD FOREIGN KEY("category_id") REFERENCES "category"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "transaction"
ADD FOREIGN KEY("customer_id") REFERENCES "customer"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "transaction"
ADD FOREIGN KEY("product_id") REFERENCES "product"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "customer"
ADD FOREIGN KEY("city_id") REFERENCES "city"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "transaction"
ADD FOREIGN KEY("supplier_id") REFERENCES "supplier"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "transaction"
ADD FOREIGN KEY("order_id") REFERENCES "order"("id")
ON UPDATE cascade ON DELETE cascade;


`);

    
        await client.query('COMMIT');

        
    } catch (error) {
        await client.query('ROLLBACK');
        throw error;
    } finally {
        client.release();
    }
}



export async function queryData() {
    const client = await pool.connect();
    
    try {
        await client.query('BEGIN');

        const result = [];
        await new Promise((resolve, reject) => {
            fs.createReadStream(env.fileDataCsv)    
                .pipe(csv())                          
                .on("data", (data) => result.push(data))  
                .on("end", resolve)                   
                .on("error", reject);                 
        });
        
        
        const counters = {
            countCustomers: 0,
            countProducts: 0,
            countCategories: 0,
            countSuppliers: 0,
            countOrders: 0,
            countTransactions: 0
        };
        
        for (const row of result) {
            

        
            const customerName = row.customer_name
                .trim()                              
                .replace(/\s+/g, ' ')                
                .split(' ')                          
                .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())  
                .join(' ');                         
           
            
            const customerEmail = row.customer_email.trim().toLowerCase();
            const customerAdress = row.customer_address.trim();
            const customerCity = row.city.trim();
            const customerPhone = row.customer_phone.trim();
            const supplierName = row.supplier_name.trim();
            const supplierEmail = row.supplier_email.trim().toLowerCase();
            const categoryName = row.product_category.trim();
            const productSku = row.product_sku.trim().toUpperCase();
            const productName = row.product_name.trim();
            const unitPrice = parseInt(row.unit_price); 
            const quantity = parseInt(row.quantity);
            const totalLineValue = parseInt(row.total_line_value);
            const orderId = row.transaction_id.trim().toUpperCase(); 
            const transactionDate = new Date(row.date);          

            const city_result = await client.query(`
                INSERT INTO "city" ("name") 
                VALUES ($1) 
                ON CONFLICT ("name")
                DO UPDATE SET name = EXCLUDED.name
                RETURNING xmax
            `, [customerCity]);

            const cityId = await client.query(
                `SELECT id FROM city WHERE name = $1`, 
                [customerCity]
            );


            const customer_result = await client.query(`
                INSERT INTO "customer" ("name", "email", "phone", "address", "city_id") 
                VALUES ($1, $2, $3, $4, $5) 
                ON CONFLICT ("email")
                DO UPDATE SET name = EXCLUDED.name, phone = EXCLUDED.phone, address = EXCLUDED.address
                RETURNING xmax
            `, [customerName, customerEmail, customerPhone, customerAdress, cityId.rows[0].id]);
            

            const supplier_result = await client.query(`
                INSERT INTO "supplier" ("name", "email") 
                VALUES ($1, $2) 
                ON CONFLICT ("email")
                DO UPDATE SET name = EXCLUDED.name
                RETURNING xmax
            `, [supplierName, supplierEmail]);



            const category_result = await client.query(`
                INSERT INTO "category" ("name") 
                VALUES ($1) 
                ON CONFLICT ("name")
                DO UPDATE SET name = EXCLUDED.name
                RETURNING xmax
            `, [categoryName]);


            const categoryId = await client.query(
                `SELECT id FROM category WHERE name = $1`, 
                [categoryName]
            );


            const product_result = await client.query(`
                INSERT INTO "product" ("id", "name", "price", "category_id") 
                VALUES ($1, $2, $3, $4)
                ON CONFLICT ("id")
                DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, category_id = EXCLUDED.category_id
                RETURNING xmax
            `, [productSku, productName, unitPrice, categoryId.rows[0].id]);
            

            const supplierID = await client.query(
                `select id from supplier where email = $1
                `, [supplierEmail]
            )
            const order_result = await client.query(`
                INSERT INTO "order" ("id", "date") 
                VALUES ($1, $2) 
                ON CONFLICT ("id")
                DO UPDATE SET date = EXCLUDED.date
                RETURNING xmax
            `, [orderId, transactionDate]);

            const customerID = await client.query(
                `select id from customer where email = $1
                `, [customerEmail]
            )
            
            
            const transaction_result = await client.query(`
                INSERT INTO "transaction" ("quantity", "total_value", "product_id", "supplier_id", "order_id", "customer_id") 
                VALUES ($1, $2, $3, $4, $5, $6) 
                ON CONFLICT ("product_id", "order_id")
                DO UPDATE SET quantity = EXCLUDED.quantity, total_value = EXCLUDED.total_value, product_id = EXCLUDED.product_id, supplier_id = EXCLUDED.supplier_id, customer_id = EXCLUDED.customer_id
                RETURNING xmax
            `, [quantity, totalLineValue, productSku, supplierID.rows[0].id, orderId, customerID.rows[0].id]);


            await customerSchema.findOneAndUpdate(
                { "customerEmail": customerEmail }, 
                {

                    $setOnInsert: {
                        "customerEmail": customerEmail,
                        "customerName": customerName,
                                  },
                    $push: {
                        "orderHistory": {
                            "orderId": orderId,
                            "date": transactionDate,
                            "products": [
                                {
                                    "productSku": productSku,
                                    "productName": productName,
                                    "quantity": quantity,
                                    "unitPrice": unitPrice,
                                    "totalValue": totalLineValue,
                                }
                            ]
                        }
                    }
                },
                { upsert: true } 
           
            );
            
            if (customer_result.rows[0].xmax === '0') counters.countCustomers++;
            if (supplier_result.rows[0].xmax === '0') counters.countSuppliers++;
            if (product_result.rows[0].xmax === '0') counters.countProducts++;
            if (category_result.rows[0].xmax === '0') counters.countCategories++;
            if (order_result.rows[0].xmax === '0') counters.countOrders++;
            if (transaction_result.rows[0].xmax === '0') counters.countTransactions++;
            }

        await client.query('COMMIT');
        return counters;

    } catch (error) {
        console.log('Error en migración:', error);
        await client.query('ROLLBACK');
        throw error;
    } finally {
        client.release();
    }
}