import { pool } from "../config/postgres.js";


export async function queryTables() {
    const client = await pool.connect();
        try {
        await client.query('BEGIN');

        await client.query(`
            CREATE TABLE IF NOT EXISTS "cliente" (
	"	id serial [ pk, not null, unique ]
	nombre_cliente varchar [ not null ]
	email_cliente varchar [ not null ]
	dirrecion varchar [ not null ]
	compra_producto integer [ not null ]
	"fecha de venta" date
);
        `);
        await client.query(`
            
CREATE TABLE IF NOT EXISTS "producto" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);
        `);

    
        await client.query(`
    CREATE TABLE IF NOT EXISTS "provedor" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);


`);
    


        await client.query(`
ALTER TABLE "product"
ADD FOREIGN KEY("category_id") REFERENCES "category"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "transaction"
ADD FOREIGN KEY("customer_id") REFERENCES "customer"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "transaction"
ADD FOREIGN KEY("product_id") REFERENCES "product"("id")
ON UPDATE cascade ON DELETE cascade;
ALTER TABLE "customer"
`);

    
        await client.query('COMMIT');
        
    } catch (error) {
        
        await client.query('ROLLBACK');
        throw error;
    } finally {
        
        client.release();
    }
}